// GENERATED by scripts/build-api-papers.mjs — do not edit.
// Source of truth is src/data/papers.ts. See that script's header for why this
// file exists at all rather than the function importing papers.ts directly.

export const PAPERS = [
  {
    "slug": "class-12-physics",
    "subject": "Physics",
    "code": "042",
    "grade": 12,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Electrostatics",
        "marks": 10,
        "asked": "Field and potential from charge distributions, Gauss’s law, capacitors in combination. Ten marks, heavily numerical, and the unit I personally lost the most on."
      },
      {
        "n": 2,
        "name": "Current Electricity",
        "marks": 6,
        "asked": "Drift velocity, Kirchhoff’s laws, the Wheatstone bridge, potentiometer."
      },
      {
        "n": 3,
        "name": "Magnetic Effects of Current and Magnetism",
        "marks": 11,
        "asked": "Biot–Savart and Ampère’s law, force on conductors, torque on a loop, the moving coil galvanometer. Second-heaviest unit in the paper."
      },
      {
        "n": 4,
        "name": "Electromagnetic Induction and Alternating Current",
        "marks": 6,
        "asked": "Faraday and Lenz, self and mutual inductance, LCR circuits, the transformer."
      },
      {
        "n": 5,
        "name": "Electromagnetic Waves",
        "marks": 4,
        "asked": "Almost pure recall — the spectrum in order, and the uses and sources of each band. Four marks for memorising one table."
      },
      {
        "n": 6,
        "name": "Optics",
        "marks": 14,
        "asked": "The heaviest unit by a distance. Ray optics — mirrors, lenses, the lens maker formula, microscopes and telescopes — plus wave optics: interference, Young’s double slit, diffraction."
      },
      {
        "n": 7,
        "name": "Dual Nature of Radiation and Matter",
        "marks": 4,
        "asked": "Photoelectric effect and de Broglie wavelength. Small, self-contained, and a frequent case study."
      },
      {
        "n": 8,
        "name": "Atoms and Nuclei",
        "marks": 8,
        "asked": "Bohr’s model and spectral series, then binding energy per nucleon, fission and fusion. More conceptual than most of the paper."
      },
      {
        "n": 9,
        "name": "Electronic Devices",
        "marks": 7,
        "asked": "Semiconductors, p-n junctions, diodes and rectifiers, energy band diagrams. Short syllabus, seven marks, and rarely tricky."
      }
    ]
  },
  {
    "slug": "class-12-chemistry",
    "subject": "Chemistry",
    "code": "043",
    "grade": 12,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Solutions",
        "marks": 7,
        "asked": "Colligative properties, and almost always a numerical — molality, elevation of boiling point, depression of freezing point, or a van’t Hoff factor question."
      },
      {
        "n": 2,
        "name": "Electrochemistry",
        "marks": 9,
        "asked": "The heaviest unit in the paper, and the one the 2026 paper leaned on hardest. Nernst equation, cell EMF, conductivity and molar conductivity, and electrolysis calculations."
      },
      {
        "n": 3,
        "name": "Chemical Kinetics",
        "marks": 7,
        "asked": "Rate law and order, the first-order integrated rate equation, half-life, and Arrhenius. Reliably numerical."
      },
      {
        "n": 4,
        "name": "d- and f-Block Elements",
        "marks": 7,
        "asked": "Reason-based questions: why this oxidation state, why that colour, why this magnetic moment. Lanthanoid contraction turns up constantly."
      },
      {
        "n": 5,
        "name": "Coordination Compounds",
        "marks": 7,
        "asked": "IUPAC naming, isomerism, and crystal field theory — hybridisation, geometry, magnetic behaviour. Very predictable once you have done thirty of them."
      },
      {
        "n": 6,
        "name": "Haloalkanes and Haloarenes",
        "marks": 6,
        "asked": "SN1 versus SN2 reasoning, reactivity order, and named conversions."
      },
      {
        "n": 7,
        "name": "Alcohols, Phenols and Ethers",
        "marks": 6,
        "asked": "Distinction tests, acidity comparisons, and mechanism-flavoured conversions."
      },
      {
        "n": 8,
        "name": "Aldehydes, Ketones and Carboxylic Acids",
        "marks": 8,
        "asked": "The biggest organic unit. Named reactions, distinguishing tests, and a conversion chain almost every year."
      },
      {
        "n": 9,
        "name": "Amines",
        "marks": 6,
        "asked": "Basicity order with reasons, diazotisation, and identification tests."
      },
      {
        "n": 10,
        "name": "Biomolecules",
        "marks": 7,
        "asked": "Almost pure recall — carbohydrates, proteins, vitamins, nucleic acids. The cheapest marks in the paper."
      }
    ]
  },
  {
    "slug": "class-12-maths",
    "subject": "Mathematics",
    "code": "041",
    "grade": 12,
    "theoryMarks": 80,
    "internalMarks": 20,
    "units": [
      {
        "n": 1,
        "name": "Relations and Functions",
        "marks": 8,
        "asked": "One-one and onto proofs, and inverse trigonometric functions. Almost always a five-marker asking you to prove a function bijective."
      },
      {
        "n": 2,
        "name": "Algebra",
        "marks": 10,
        "asked": "Matrices and determinants — inverse by adjoint, and solving a system of three equations as a matrix product."
      },
      {
        "n": 3,
        "name": "Calculus",
        "marks": 35,
        "asked": "Nearly half the paper. Continuity and differentiability, applications of derivatives, indefinite and definite integrals, area under curves, and differential equations."
      },
      {
        "n": 4,
        "name": "Vectors and Three-Dimensional Geometry",
        "marks": 14,
        "asked": "Dot and cross products, projections, and the shortest distance between two lines — which turns up nearly every year."
      },
      {
        "n": 5,
        "name": "Linear Programming",
        "marks": 5,
        "asked": "One question, graphical method, corner points. The most predictable five marks in the paper and the reason the booklet has graph paper in it."
      },
      {
        "n": 6,
        "name": "Probability",
        "marks": 8,
        "asked": "Conditional probability, Bayes, and a case study built around a real-sounding scenario."
      }
    ]
  },
  {
    "slug": "class-12-english",
    "subject": "English Core",
    "code": "301",
    "grade": 12,
    "theoryMarks": 80,
    "internalMarks": 20,
    "units": [
      {
        "n": 1,
        "name": "Reading Comprehension",
        "marks": 22,
        "asked": "Two unseen passages with sub-parts. No preparation possible beyond reading carefully and answering in the passage’s own words."
      },
      {
        "n": 2,
        "name": "Creative Writing Skills",
        "marks": 18,
        "asked": "Notice, invitation, letter to the editor or application, and an article or report. Fixed layouts, fixed mark distribution."
      },
      {
        "n": 3,
        "name": "Literature",
        "marks": 40,
        "asked": "Flamingo and Vistas — extract-based questions, short answers and two long answers on theme and character."
      }
    ]
  },
  {
    "slug": "class-12-computer-science",
    "subject": "Computer Science",
    "code": "083",
    "grade": 12,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Computational Thinking and Programming — 2",
        "marks": 40,
        "asked": "Python: functions, file handling (text, binary and CSV), and data structures — the stack especially. Well over half the paper."
      },
      {
        "n": 2,
        "name": "Computer Networks",
        "marks": 10,
        "asked": "Topologies, devices, protocols, and one case study asking you to lay out a campus network and justify it."
      },
      {
        "n": 3,
        "name": "Database Management",
        "marks": 20,
        "asked": "SQL queries and their output tables, plus Python–MySQL connectivity. Very predictable and very learnable."
      }
    ]
  },
  {
    "slug": "class-11-physics",
    "subject": "Physics",
    "code": "042",
    "grade": 11,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Measurement, kinematics and laws of motion",
        "marks": 23,
        "asked": "CBSE marks Units I–III as a single block of 23 — Units and Measurements, Motion in a Straight Line, Motion in a Plane, Laws of Motion. A third of the paper, almost entirely numerical, and the part everything later in the year is built on."
      },
      {
        "n": 2,
        "name": "Work, energy, power and rotational motion",
        "marks": 17,
        "asked": "Units IV–V together — work–energy theorem, conservation of energy, collisions, then centre of mass, torque, moment of inertia and angular momentum. Rotational motion is the hardest thing in the Class 11 course and it is not learnable in an evening."
      },
      {
        "n": 3,
        "name": "Gravitation, bulk matter, thermodynamics and kinetic theory",
        "marks": 20,
        "asked": "Units VI–IX as one block of 20 — gravitation, mechanical properties of solids and fluids, thermal properties, thermodynamics, kinetic theory. Broad rather than deep, and a lot of it is standard results you can hold in your head."
      },
      {
        "n": 4,
        "name": "Oscillations and waves",
        "marks": 10,
        "asked": "SHM and its energy, the simple pendulum, then wave motion, superposition, standing waves and beats. Self-contained — you can do this one without the rest of the syllabus, which is rare."
      }
    ]
  },
  {
    "slug": "class-11-chemistry",
    "subject": "Chemistry",
    "code": "043",
    "grade": 11,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Some Basic Concepts of Chemistry",
        "marks": 7,
        "asked": "The mole concept, molar mass, empirical and molecular formulae, and stoichiometry. Seven marks, but it is the arithmetic the rest of the subject runs on — being shaky here costs you marks in units it is not even about."
      },
      {
        "n": 2,
        "name": "Structure of Atom",
        "marks": 9,
        "asked": "Bohr’s model and its limits, de Broglie, the Heisenberg principle, quantum numbers, orbital shapes, and filling order — Aufbau, Pauli, Hund."
      },
      {
        "n": 3,
        "name": "Classification of Elements and Periodicity",
        "marks": 6,
        "asked": "Periodic trends and the reasoning behind them: atomic radius, ionisation enthalpy, electron gain enthalpy, electronegativity. Six marks of almost pure recall — the cheapest marks in the paper when you are short of hours."
      },
      {
        "n": 4,
        "name": "Chemical Bonding and Molecular Structure",
        "marks": 7,
        "asked": "Lewis structures, VSEPR shapes, valence bond theory and hybridisation, molecular orbital theory for simple diatomics, and hydrogen bonding."
      },
      {
        "n": 5,
        "name": "Chemical Thermodynamics",
        "marks": 9,
        "asked": "Internal energy, enthalpy and Hess’s law, entropy, and Gibbs free energy as the criterion for spontaneity. Nine marks and heavily numerical."
      },
      {
        "n": 6,
        "name": "Equilibrium",
        "marks": 7,
        "asked": "Both halves — the equilibrium constant and Le Chatelier, then ionic equilibrium: pH, buffers, solubility product, and the acid–base theories."
      },
      {
        "n": 7,
        "name": "Redox Reactions",
        "marks": 4,
        "asked": "Oxidation numbers, balancing redox equations by the half-reaction method, and redox titration basics. Small, mechanical, and quick to secure."
      },
      {
        "n": 8,
        "name": "Organic Chemistry: Basic Principles and Techniques",
        "marks": 11,
        "asked": "The largest single unit — IUPAC naming, isomerism, and the reaction mechanism vocabulary the whole of organic chemistry then assumes: inductive and resonance effects, electrophiles and nucleophiles, and the three kinds of bond fission."
      },
      {
        "n": 9,
        "name": "Hydrocarbons",
        "marks": 10,
        "asked": "Alkanes, alkenes, alkynes and aromatics — preparation, properties, and the named reactions. Ten marks that reward memorising a reaction map more than they reward understanding."
      }
    ]
  },
  {
    "slug": "class-11-maths",
    "subject": "Mathematics",
    "code": "041",
    "grade": 11,
    "theoryMarks": 80,
    "internalMarks": 20,
    "units": [
      {
        "n": 1,
        "name": "Sets and Functions",
        "marks": 23,
        "asked": "Sets and their operations, relations and functions with domain and range, and then trigonometric functions — identities, general solutions, and graphs. Trigonometry is most of the block and most of the difficulty."
      },
      {
        "n": 2,
        "name": "Algebra",
        "marks": 25,
        "asked": "The biggest block in the paper: complex numbers, linear inequalities, permutations and combinations, the binomial theorem, and sequences and series. Five separate topics that share nothing except the mark pool."
      },
      {
        "n": 3,
        "name": "Coordinate Geometry",
        "marks": 12,
        "asked": "Straight lines, then conic sections — circle, parabola, ellipse, hyperbola — and an introduction to three-dimensional geometry. Formula-heavy and very learnable in a night if you have the formula list."
      },
      {
        "n": 4,
        "name": "Calculus",
        "marks": 8,
        "asked": "Limits, derivatives from first principles, and the standard differentiation rules. Only eight marks here, but it is the foundation the whole of Class 12 calculus — 35 marks of it — sits on."
      },
      {
        "n": 5,
        "name": "Statistics and Probability",
        "marks": 12,
        "asked": "Mean deviation, variance and standard deviation, then basic probability. Almost entirely formula-and-substitute. Twelve marks at the lowest effort per mark in the paper."
      }
    ]
  },
  {
    "slug": "class-11-english",
    "subject": "English Core",
    "code": "301",
    "grade": 11,
    "theoryMarks": 80,
    "internalMarks": 20,
    "units": [
      {
        "n": 1,
        "name": "Reading Skills",
        "marks": 26,
        "asked": "Two unseen passages, then note-making and a summary. Twenty-six marks that no amount of revision touches — but note-making is a fixed format worth 5, and that part you can practise."
      },
      {
        "n": 2,
        "name": "Grammar and Creative Writing Skills",
        "marks": 23,
        "asked": "Seven marks of grammar — gap filling, clauses, transformation — and sixteen of writing: classified advertisement, poster, speech, debate. Every one of those four has a published layout with the marks split between format, content and expression."
      },
      {
        "n": 3,
        "name": "Literature — Hornbill and Snapshots",
        "marks": 31,
        "asked": "Extract-based questions on prose and poetry, short answers of 40–50 words, and long answers. Thirty-one marks, and the only part of this paper where knowing the chapters is what scores."
      }
    ]
  },
  {
    "slug": "class-11-computer-science",
    "subject": "Computer Science",
    "code": "083",
    "grade": 11,
    "theoryMarks": 70,
    "internalMarks": 30,
    "units": [
      {
        "n": 1,
        "name": "Computer Systems and Organisation",
        "marks": 10,
        "asked": "Hardware and software, the memory hierarchy and its units, what an operating system does, Boolean logic with truth tables and De Morgan’s laws, and number system conversions. Ten marks, and most of it is a table you can learn."
      },
      {
        "n": 2,
        "name": "Computational Thinking and Programming — 1",
        "marks": 45,
        "asked": "Forty-five of the seventy marks. Python from the start: data types, operators, control flow, strings, lists, tuples and dictionaries. This is a skill rather than a syllabus — it does not go in overnight, and the honest move the night before is to secure the other twenty-five marks first."
      },
      {
        "n": 3,
        "name": "Society, Law and Ethics",
        "marks": 15,
        "asked": "Digital footprints, netiquette, intellectual property and licensing, cybercrime, the IT Act, e-waste, and health concerns around technology. Fifteen marks of straight recall, and by a distance the best value in the paper on a short night."
      }
    ]
  }
]

export const paperBySlug = (slug) => PAPERS.find((p) => p.slug === slug)
